In [2]:
import numpy as np

### Creating Array

In [3]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
a[0, 3:5]

array([4, 5])

In [5]:
a[:, 2]

array([ 3,  8, 13])

In [6]:
a[2::2 , ::2]

array([[11, 13, 15]])

In [7]:
np.where(a > 7, a, 0)

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Shape and Reshape

In [8]:
a.shape

(3, 5)

In [9]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b.shape

(2, 3)

In [11]:
np.reshape(b, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
np.reshape(b, (1, -1))
# n columns and 1 rows

array([[1, 2, 3, 4, 5, 6]])

In [13]:
np.reshape(b, (-1, 1))
# 1 column and n rows

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### Arrays in numpy

In [14]:
a.ndim

2

In [15]:
a.dtype

dtype('int32')

In [16]:
c = np.array([
    [1,2,3],
    [4,5,6]
], dtype=np.float32)
c

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [17]:
c.size

6

In [18]:
c.itemsize

4

### arange in numpy

In [19]:
np.arange(1, 20, step=4)

array([ 1,  5,  9, 13, 17])

### linspace in numpy

In [20]:
np.linspace(0,1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Creating Specific arrays
    - np.zeros
    - np.ones
    - np.full
    - np.eye

In [21]:
np.ones(shape=(3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
5 * np.ones(shape=(3, 2), dtype=np.int32)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [24]:
np.full((3, 2), 5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.fliplr(np.eye(5))

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [27]:
np.random.rand(3,2)

array([[0.2085469 , 0.54645239],
       [0.92267614, 0.67895653],
       [0.02524383, 0.93703141]])

### Operations in numpy

In [28]:
x = np.array([
    [1,2],
    [3,4]
], dtype=np.float64)

y = np.array([
    [5,6],
    [7,8]
], dtype=np.float64)

print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [29]:
print(x+y)
print(np.add(x, y)) # better performance becuse of C++ codes of numpy

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [30]:
print(x-y)
print(np.subtract(x, y)) # better performance becuse of C++ codes of numpy

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [31]:
print(x*y)
print(np.multiply(x, y)) # better performance becuse of C++ codes of numpy

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [32]:
print(x/y)
print(np.divide(x, y)) # better performance becuse of C++ codes of numpy

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [33]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

### Adding, Sorting

In [34]:
arr = np.array([2,4,6,8,2,3,4,6])
arr

array([2, 4, 6, 8, 2, 3, 4, 6])

In [35]:
np.sort(arr)

array([2, 2, 3, 4, 4, 6, 6, 8])

In [36]:
np.concatenate((x,y))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [38]:
arr.max()

8

In [39]:
arr.sum()

35

In [40]:
arr.min()

2

In [42]:
x.max(axis=0)

array([3., 4.])

### Flatten() vs. Ravel()

In [47]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
b.flatten()
# like reshape in memory

array([1, 2, 3, 4, 5, 6])

In [49]:
b.ravel()
# like reshape not in memory

array([1, 2, 3, 4, 5, 6])

In [52]:
np.random.choice([i for i in range(101)])

27