In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

In [4]:
dataset = pd.read_csv("Churn_Modelling.csv")
dataset.sample(10)

RowNumber  CustomerId     Surname  CreditScore Geography  Gender  Age  \
1297       1298    15793247     Hancock          498    France    Male   34   
8691       8692    15632439       Pinto          698    France  Female   39   
4532       4533    15739194     Manfrin          548     Spain    Male   38   
7704       7705    15796336       Chang          786     Spain  Female   34   
2980       2981    15709476      Kenyon          850     Spain  Female   41   
7301       7302    15702149       Fomin          767   Germany  Female   33   
6715       6716    15763111         Niu          808     Spain  Female   67   
5775       5776    15717527   Ifeanacho          619    France  Female   49   
7855       7856    15663808  Ifesinachi          666   Germany  Female   59   
8553       8554    15791321       Nwora          682     Spain  Female   58   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
1297       5       0.00              2          1               1   
8691       4       0.00              2          0               1   
4532       0  178056.54              2          1               0   
7704       9       0.00              2          1               0   
2980       3   99945.93              2          1               0   
7301       1  144753.21              1          1               1   
6715      10  124577.15              1          0               1   
5775       9  145359.99              1          1               0   
7855       8  152614.51              2          1               1   
8553       4       0.00              1          1               0   

      EstimatedSalary  Exited  
1297         91711.66       0  
8691         47455.82       0  
4532         38434.73       0  
7704        117034.32       0  
2980         71179.31       0  
7301        132480.75       0  
6715        169894.40       0  
5775         38186.85       0  
7855        188782.30       0  
8553        176036.01       0

In [6]:
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
x[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10) 

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [14]:
x_train

array([[-1.00551521,  1.73436329, -0.57388614, ...,  0.64007158,
         0.97530483, -0.56087335],
       [-1.00551521, -0.57658047,  1.74250594, ...,  0.64007158,
         0.97530483, -0.156221  ],
       [-1.00551521, -0.57658047,  1.74250594, ...,  0.64007158,
        -1.02532046,  1.56921791],
       ...,
       [-1.00551521,  1.73436329, -0.57388614, ...,  0.64007158,
        -1.02532046, -0.14906952],
       [ 0.99451504, -0.57658047, -0.57388614, ...,  0.64007158,
        -1.02532046, -0.7496959 ],
       [-1.00551521,  1.73436329, -0.57388614, ...,  0.64007158,
        -1.02532046, -1.71929584]])

In [15]:
x_test

array([[-0.99203175,  1.70253795, -0.57350122, ..., -1.49191369,
         0.95023659,  1.23617881],
       [-0.99203175, -0.58735842,  1.74367544, ...,  0.67028006,
        -1.0523695 ,  1.16555881],
       [-0.99203175, -0.58735842,  1.74367544, ...,  0.67028006,
        -1.0523695 ,  1.70008653],
       ...,
       [-0.99203175, -0.58735842,  1.74367544, ...,  0.67028006,
        -1.0523695 ,  0.04120296],
       [ 1.00803226, -0.58735842, -0.57350122, ...,  0.67028006,
         0.95023659, -1.63016947],
       [-0.99203175, -0.58735842,  1.74367544, ..., -1.49191369,
         0.95023659, -0.32783138]])

In [16]:
ann = tf.keras.models.Sequential()

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [21]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [22]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7891
Epoch 2/100
250/250 [==============================] - 0s 845us/step - loss: 0.4619 - accuracy: 0.7981
Epoch 3/100
250/250 [==============================] - 0s 793us/step - loss: 0.4327 - accuracy: 0.7994
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4197 - accuracy: 0.8025
Epoch 5/100
250/250 [==============================] - 0s 857us/step - loss: 0.4109 - accuracy: 0.8096
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4019 - accuracy: 0.8170
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3907 - accuracy: 0.8344
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3786 - accuracy: 0.8400
Epoch 9/100
250/250 [==============================] - 0s 959us/step - loss: 0.3696 - accuracy: 0.8445
Epoch 10/100
250/250 [==============================] - 0s 887us/step - loss: 0.363

In [24]:
y_pred = ann.predict(x_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 0]
 [1 1]
 ...
 [0 1]
 [0 0]
 [1 1]]


In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1521   57]
 [ 244  178]]


0.8495